"""
Django settings for blood_network project.
Generated by 'django-admin startproject' using Django 6.0.2.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load the hidden variables from your .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
# (It will now read this securely from your .env file)
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-4*ybl=9jmmd5!1bm@+t_n3u&t3ix=-7gd6$$m-2gu25q+q5_5s')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# Allow all hosts so Render/Railway can easily connect
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis', # Geographic support
    'core',               # Your main app
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware", # MUST BE RIGHT HERE FOR PRODUCTION
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "blood_network.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "blood_network.wsgi.application"


# Database
# For now, it remains connected to your local pgAdmin. 
# We will swap this to Supabase later!
import dj_database_url

# Database connection logic
DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    # ☁️ CLOUD: This uses the Supabase URL from your .env
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            engine='django.contrib.gis.db.backends.postgis',
            conn_max_age=600
        )
    }
else:
    # 💻 LOCAL: Fallback to your local machine
    DATABASES = {
        'default': {
            'ENGINE': 'django.contrib.gis.db.backends.postgis',
            'NAME': 'blood_donor_db',
            'USER': 'postgres',
            'PASSWORD': 'muhitiNix442',
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    { "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator", },
    { "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", },
    { "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator", },
    { "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator", },
]


# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"

# REQUIRED FOR PRODUCTION: Tells WhiteNoise where to bundle your files
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Windows GeoDjango Configuration
if os.name == 'nt':
    GEOS_LIBRARY_PATH = r'C:\Program Files\PostgreSQL\17\bin\libgeos_c.dll'
    GDAL_LIBRARY_PATH = r'C:\Program Files\PostgreSQL\17\bin\libgdal-35.dll'